name: testenv
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.6
  - pip
  - numpy
  - scipy
  - matplotlib
  - netcdf4
  - pytest
  - pytest-mpl
  - pytest-cov
  - dask
  - flake8
  - act-atmos
  - pint
  - pip:
    - pymiescatt
